---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Reload wireguard tunnel
  ansible.builtin.shell: |
    set -o pipefail
    wg syncconf "{{ item.interface }}" <(wg-quick strip "{{ item.interface }}")
  args:
    executable: /bin/bash
  loop: "{{ wireguard_tunnels }}"
  changed_when: true

- name: Restart wireguard exporter
  ansible.builtin.systemd:
    name: "{{ wireguard_exporter_service }}"
    state: restarted
