---
- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart smartctl exporter
  ansible.builtin.systemd:
    name: smartctl_exporter
    daemon_reload: true
    state: restarted
