---
node_exporter_package: prometheus-node-exporter
node_exporter_service: prometheus-node-exporter
node_exporter_args_file: /etc/conf.d/prometheus-node-exporter
node_exporter_args_var: NODE_EXPORTER_ARGS
