---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart nginx exporter
  ansible.builtin.systemd:
    name: "{{ nginx_exporter_service }}"
    state: restarted
