---
- name: Restart NUT driver enumerator
  ansible.builtin.systemd:
    name: nut-driver-enumerator.service
    state: restarted

- name: Restart NUT server
  ansible.builtin.systemd:
    name: nut-server.service
    state: restarted

- name: Restart NUT monitor
  ansible.builtin.systemd:
    name: nut-monitor.service
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart NUT exporter
  ansible.builtin.systemd:
    name: "{{ nut_prometheus_exporter_service }}"
    state: restarted
