---
- name: Restart NUT driver enumerator
  ansible.builtin.systemd:
    name: nut-driver-enumerator.service
    state: restarted

- name: Restart NUT server
  ansible.builtin.systemd:
    name: nut-server.service
    state: restarted

- name: Restart NUT monitor
  ansible.builtin.systemd:
    name: nut-monitor.service
    state: restarted
