---
ssh_port: 22
ssh_allowed_networks:
  - { src: "192.168.1.0/24", comment: "SSH from LAN" }
  - { src: "192.168.27.0/27", comment: "SSH from VPN" }
ssh_users: "jokester" # space separated if many
ssh_config_dir: "/etc/ssh"
sshd_config: "{{ ssh_config_dir }}/sshd_config"
sshd_banner: "{{ ssh_config_dir }}/banner"
sshd_binary: "/usr/sbin/sshd"
ssh_authorized_keys_fallback_enabled: false
ssh_authorized_keys_fallback_dir: "/etc/ssh/authorized_keys"
